sudo: false
cache:
  directories:
    - $HOME/.m2

language: java
script: "mvn verify"
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installerbefore_install:
  - wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
  - unzip -qq apache-maven-3.3.9.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH
